services:
  multify:
    build: .
    container_name: multify
    restart: unless-stopped
    ports:
      - "5099:5099"
    volumes:
      - ./data:/app/data
    environment:
      - CONFIG_FILE=/app/data/config.json
